bycycle-tools/bycycle

bycycle/burst.py
bycycle/features.py

Currently plots within the function and returns None, but this makes it difficult to change aspects of the plot.
I tested, and this change should not significantly break any old code. If no output is specified, the axes will just be printed to the screen in my Jupyter notebook.
I suppose if someone is running this in a script, now `plt.show()` will never be called, and so the plot may never appear.

When plotting burst detection parameters, return axes

---

.travis.yml
examples/plot_mne_feature_distributions.py
examples/plot_pac_feature_distributions.py
requirements-docs.txt

It might be helpful to mne-python users to have an example of an interface with bycycle as in this example for a [pac toolbox](https://pactools.github.io/auto_examples/plot_mne_epoch_masking.html). I also added a bit out of curiosity using the pac simulation for both pac simulated as expected and "spurious" pac caused by spiking. The peak-trough asymmetry is lower in both the particular example of pac and spurious pac compared to a sine wave with pink noise while rise-decay asymmetry is closer to the same for all three but a bit skewed positive for spurious pac. I think this means it's working reasonably well? If the spurious pac spike amplitude gets increased, the same trend holds while it just looks like a spike train. I'm not entirely sure how to interpret this, maybe someone can …

mne interface example

---

bycycle/features/burst.py

This is related to #42. The issue involved warnings when computing monotonicity. This occurred when `sample_last_trough` and `sample_peak` (or `sample_peak` and `sample_next_trough` for decay periods) are adjacent. This should be fixed be adding one to the end slice index. The `rise_period` should include the start/end point, otherwise the segments directly to the left/right of the peak are left out when taking the np.diff of the rise and decay periods. Here is sample code to reproduce the warning:
```
from neurodsp.filt import filter_signal
from bycycle.plts import plot_burst_detect_summary
from bycycle.features import compute_features
sigs = np.load('tutorials/data/sim_experiment.npy')
sig = sigs[0]
fs = 1000
sig = filter_signal(sig, fs, 'lowpass', 30, n_seconds=.2, …
```

[BUG] Monotonicity Warning

---

bycycle/cyclepoints/zerox.py

Whenever a signal has an exact zero-crossing, there would be an off-by-one error. This PR fixes this.
```
from neurodsp.plts import plot_time_series
from neurodsp.sim import sim_oscillation
from bycycle.cyclepoints import find_extrema
from bycycle.cyclepoints.zerox import find_zerox, find_flank_zerox
fs, f_range = 500, (8, 12)
sig = sim_oscillation(.5, fs, 10)
sig = np.round(sig, decimals=3)
sig[:50] = 0.0
sig[-50:] = 0.0
times = np.arange(0, len(sig)/fs, 1/fs)
rises_flank = find_flank_zerox(sig, 'rise')
peaks, troughs = find_extrema(sig, fs, f_range, boundary=0)
rises, decays = find_zerox(sig, peaks, troughs)
plot_time_series([times, times[rises_flank], times], [sig, sig[rises_flank], [0]*len(sig)], 
title='Rise zerox from find_flank_zerox', ls=["solid", "", 'dashed'], …
```

[BUG] Zerox off-by-one

---

bycycle/burst/amp.py
bycycle/burst/cycle.py
bycycle/burst/utils.py
bycycle/features/burst.py
bycycle/features/features.py
bycycle/features/shape.py
bycycle/group/features.py
bycycle/group/utils.py
bycycle/plts/burst.py
bycycle/tests/burst/test_amp.py
bycycle/tests/burst/test_utils.py
bycycle/tests/conftest.py
bycycle/tests/cyclepoints/test_extrema.py
bycycle/tests/cyclepoints/test_phase.py
bycycle/tests/cyclepoints/test_zerox.py
bycycle/tests/features/test_burst.py
bycycle/tests/features/test_features.py
bycycle/tests/features/test_shapes.py
bycycle/tests/group/test_features.py
bycycle/tests/group/test_utils.py
bycycle/tests/plts/test_burst.py
bycycle/tests/plts/test_cyclepoints.py
bycycle/tests/utils/test_dataframes.py
bycycle/utils/__init__.py
bycycle/utils/dataframes.py
bycycle/version.py
tutorials/plot_2_bycycle_algorithm.py
tutorials/plot_3_bycycle_resting_state.py

**2d Array**
This addresses a point in #76 and is built on top of #75 (i.e. starting from deabc11). It allows for 2d arrays to be flatten prior to computing features using `axis = None`. The resulting dataframe is split into a list of dfs corresponding to indices in the original 2d signal. This is to address edge artifacts and features miscalculations from ignoring the influence of other signals.
For example flattening 2d to 1d (`axis=None`), or treating each signal separately (`axis=0`) will result in different burst fractions (`compute_burst_fraction`):
```
df_shape_features['volt_amp'].rank() / len(df_shape_features)
```
- ``axis=1`` : Iterates over each row/signal in an array independently (i.e. for each channel
in (n_channels, n_timepoints)).
- ``axis=None`` : Flattens rows/signals …

[ENH] 2d/3d Array Improvement

---

doc/Makefile
doc/_templates/navbar.html

This allows multiple versions of documentation to be hosted on the gh-pages sites. Currently, `make html-multi` may be ran to build the local version. I'll need to implement a `make install-multi` so it will be pushed to the gh-pages branch (this may take some trial and error). Different versions may be navigated via a dropdown menu:

[WIP/DOC] Multi-version docsite

---

bycycle/burst/amp.py
bycycle/burst/cycle.py
bycycle/burst/utils.py
bycycle/cyclepoints/extrema.py
bycycle/features/burst.py
bycycle/features/cyclepoints.py
bycycle/features/features.py
bycycle/features/shape.py
bycycle/plts/burst.py
bycycle/plts/cyclepoints.py
bycycle/tests/burst/test_utils.py
bycycle/utils/__init__.py
bycycle/utils/checks.py
bycycle/utils/dataframes.py
bycycle/utils/timeseries.py
requirements.txt

This is an improvement to #73 and `recompute_edges`. Period/amplitude consistency features may now be computed in one direction for non-bursting cycles that are immediately adjacent to bursts. Before the solution was to drop thresholds for edge cycles which works but was lazier.
```python
from neurodsp.sim import sim_combined
from bycycle.features import compute_features
from bycycle.burst.utils import recompute_edges
from bycycle.plts import plot_burst_detect_summary
np.random.seed(0)
n_seconds = 10
fs = 1000
f_range = (1, 51)
components = dict(sim_bursty_oscillation=dict(freq=15, cycle='gaussian', std=1),
sim_powerlaw=dict(exponent=-2))
sig = sim_combined(n_seconds, fs, components)
times = np.arange(0, len(sig)/fs, 1/fs)
thresholds = {'amp_fraction_threshold': 0.3, …
```

[ENH] Recompute consistency features at burst edges

---

bycycle/plts/burst.py
bycycle/plts/cyclepoints.py
bycycle/utils/dataframes.py

There was a bug when using `xlim` with plotting funcs. Is was a mix up of `df['sample_last_' + side_e]` and `df['sample_next_' + side_e]` in the `limit_df` func. Here's an example:
```python
from bycycle.features import compute_features
from bycycle.plts import plot_burst_detect_summary
n_seconds = 10
fs = 1000
sig = np.random.rand(int(n_seconds * fs))
times = np.arange(0, len(sig)/fs, 1/fs)
thresholds = {'amp_fraction_threshold': 0.5,
'amp_consistency_threshold': 0.5,
'period_consistency_threshold': 0.5,
'monotonicity_threshold': 0.75,
'min_n_cycles': 3}
df_features = compute_features(sig, fs, (1, 50), threshold_kwargs=thresholds)
plot_burst_detect_summary(df_features, sig, fs, thresholds, xlim=(1, 2))
```

[BUG] Limit Dataframe Fix

---

bycycle/plts/burst.py
bycycle/plts/cyclepoints.py

This bug occurs when using `compute_features_2d` with `axis=None` (for epoched data). When cycles occur at the edge of epochs, the last trough sample will be negative and highlighting sub-threshold params would be inaccurate.

[BUG] Fix plot highlighting bug

---

bycycle/__init__.py
bycycle/objs/__init__.py
bycycle/objs/fit.py
bycycle/tests/objs/test_fit.py

This adds a simple bycycle class to keep track of various settings as attributes. The motivation for this was having to look up the default `threshold_kwargs` (needed for plotting) regularly. The conventions here follow napp. I need to add an equivalent 2d arrays.
```python
from bycycle import Bycycle
from neurodsp.sim import sim_oscillation
fs = 1000
sig = sim_oscillation(10, fs, 10)
bm = Bycycle()
bm.fit(sig, fs, (1, 100))
bm.df_features
bm.thresholds
bm.plot()
```

[MRG] Bycycle Class

---

bycycle/cyclepoints/extrema.py

This optimizes the code in `find_extrema` from O(2^N) to O(N) (i.e. exponential to linear increase in runtime with increasing signal size). A signal with 1mil samples took 4.7s to run vs 0.9s after these changes. Before, a signal with 10's of millions of samples would take several minutes to run trough `find_extrema ` before I became impatient and killed the process.

[ENH] Optimize find_extrema runtime

---

bycycle/spikes/features/gaussians.py
bycycle/spikes/objs.py
bycycle/spikes/utils.py

This inverts the heights and alpha sign when fitting peak centered spikes. The signal is inverted and then gaussians the same as for trough-centered spikes. The resulting parameters are then inverted to reflect this.
This also adds demeaning for each spike separately, to adjust the baseline of simulated gaussians.

[BUG] Invert spike fit params

---

bycycle/group/utils.py

Adds a optional description for the multiprocessing progress bar. This allows it to be reused for other purposes, with flexibility of what's displayed to the user.

[ENH] Optional progress bar description for multiprocessing

---

bycycle/features/burst.py
bycycle/features/features.py

This adds min_burst_duration as an optional input to the neurodsp's `detect_bursts_dual_threshold`. Note, this only affects the `is_burst` sample-by-sample array. `min_n_cycles` is still used for the cycle-by-cycle basis of burst detection.
@apoorva6262 let me know if this works for you or not. Note that, `min_n_cycles` should be passed to `thresold_kwargs`, as these threshold are all applied on a cycle-by-cycle basis, whereas `min_burst_duration` should be passed to `burst_kwargs` since it's a unique kwarg for `burst_method == 'amp'`.
```python
from neurodsp.sim import sim_bursty_oscillation
from neurodsp.burst import detect_bursts_dual_threshold
from neurodsp.plts import plot_bursts
from bycycle.features import compute_features
from bycycle.plts import …
```

[ENH] Add min_burst_duration

---

.github/workflows/build.yml
setup.py

Updates CI tests for:
- pinning the Ubuntu version, to maintain support of py3.6 (which fails on ubuntu-latest)
- updates the versions of the actions (which addresses future deprecations)
- adds testing and lists support for python 3.11

[MNT] - Update actions versions

---

bycycle/tests/test_persistence.py

Adds a test to ensure the computed features are consistent from version to version and from PR to PR. This is to ensure there are no changes in how features are computed without an explicit warning from a failed test. The `PERSISTENT_HASH` variable must be updated/committed when a change to the output df/array is expected. Here, the df is converted to an array, then hashed using sha-1 (same algorithm that git uses), so we don't have to track a large array/df in git history.
@TomDonoghue if this looks useful, I could eventually add a similar thing to specparam/neurodsp?

[TST] Add persistent hash test

---

bycycle/burst/amp.py
bycycle/burst/cycle.py
bycycle/burst/utils.py
bycycle/tests/burst/test_utils.py

Closes #134 
Optimizations show consistent improvement in profiling (see linked issue for more details).
@ryanhammonds while working on this PR, I had the following observations -- looking for your feedback:
1. The original function doesn't particularly care what the type of `is_burst` is. When running the test suite, I caused failures after returning a `np.ndarray` because this function is used with `pd.Series` (and potentially other array-likes such as `list`). I've updated my code to operate directly on the input object to preserve type.
2. This function originally updates AND returns the input object. Depending on the input type, this could cause unexpected behavior. However, I'm leaving it as is for fear of breaking someone's project. Let me know if you think we should establish a …

[ENH] Optimize check_min_burst_cycles

---

bycycle/plts/burst.py

Issue: for current matplotlib version >= 3.8, they have deprecated passing in a marker definition as None to line style (see note in docs [here](https://matplotlib.org/stable/api/markers_api.html)). 
This update fixes this, so that None -> "None", which is interpreted as no marker style. 
Note / to check: I'm not sure if "None" will work on all older version of matplotlib - it is possible this changes behavior / creates an error on older matplotlibs.

[BUG] - Update marker definition for newer matplotlib

---

.github/workflows/build.yml
bycycle/plts/burst.py
setup.py

This PR updates the workflow to test against 3.12, which is now available. 
Confusingly, in the workflow tests, version below 3.12 (which previously passed) are now failing - which is not happening when I run tests locally. It looks like (at least part of this) might be a plotting thing, as one of the error messages is about markerstyle. @ryanhammonds - any ideas what is happening here?
Edit - this was previously failing, but it turns out it was about #144 - now that that is merged here, it works!

[MNT] - Update workflow tests to support Python 3.12

---

bycycle/objs/fit.py

The recompute_edges method updates the dataframe in the group object, e.g. `bg[i].df_features`. Access from `bg.df_features[i]` wouldn't get updated in the process. This adds a fix.

[BUG] dataframe memory fix

---

bycycle/cyclepoints/extrema.py

In recent neurodsp updates, we got a bit stricter about filter parameters & inputs [here](https://github.com/neurodsp-tools/neurodsp/pull/322)
In the bycycle `find_extrema` function, it takes filter kwargs, and then uses any given arguments to compute the length of the filter for doing some extra padding. Because we are now stricter, some inputs can now fail (for example, as done in  tutorial # 2), if trying to pass in a specified `n_seconds` filter kwarg:
```
peaks, troughs = find_extrema(sig, fs, range, filter_kwargs={'n_seconds':n_seconds})
```
This is because the function also default `n_cycles` to 3, leading to both inputs being defined and passed in, and while this used to work, neurodsp no longer allows this kind of inconsistent input. 
To address this, this PR updates the …

[MNT] - Update filter defaults
